import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class PdfService {

  // ── Generate and save PDF ─────────────────────────────────
  static Future<File> generateNotesPdf({
    required String title,
    required String content,
    required String noteType, // 'Summary' or 'Detailed'
  }) async {
    final pdf = pw.Document();

    // Parse markdown-like content into sections
    final lines = content.split('\n');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(
            title, noteType, context),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          ..._buildContent(lines),
        ],
      ),
    );

    // Save to documents folder
    final dir =
    await getApplicationDocumentsDirectory();
    final fileName =
        '${title.replaceAll(' ', '_')}_notes.pdf';
    final file = File('${dir.path}/$fileName');
    await file.writeAsBytes(await pdf.save());

    return file;
  }

  // ── Header ────────────────────────────────────────────────
  static pw.Widget _buildHeader(
      String title,
      String noteType,
      pw.Context context,
      ) {
    return pw.Container(
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(
            color: PdfColor.fromInt(0xFFD81B60),
            width: 2,
          ),
        ),
      ),
      padding:
      const pw.EdgeInsets.only(bottom: 10),
      child: pw.Row(
        mainAxisAlignment:
        pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'NoteMate',
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromInt(0xFFD81B60),
            ),
          ),
          pw.Text(
            '$noteType Notes',
            style: pw.TextStyle(
              fontSize: 12,
              color: PdfColors.grey,
            ),
          ),
        ],
      ),
    );
  }

  // ── Footer ────────────────────────────────────────────────
  static pw.Widget _buildFooter(
      pw.Context context) {
    return pw.Container(
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(
            color: PdfColors.grey300,
            width: 1,
          ),
        ),
      ),
      padding: const pw.EdgeInsets.only(top: 8),
      child: pw.Row(
        mainAxisAlignment:
        pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by NoteMate',
            style: const pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey,
            ),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey,
            ),
          ),
        ],
      ),
    );
  }

  // ── Content builder — parses markdown ─────────────────────
  static List<pw.Widget> _buildContent(
      List<String> lines) {
    final widgets = <pw.Widget>[];

    for (final line in lines) {
      if (line.trim().isEmpty) {
        widgets.add(pw.SizedBox(height: 8));
        continue;
      }

      // H1 heading
      if (line.startsWith('# ')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(
                bottom: 12, top: 16),
            child: pw.Text(
              line.substring(2),
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
                color:
                PdfColor.fromInt(0xFF1A1A2E),
              ),
            ),
          ),
        );
      }

      // H2 heading
      else if (line.startsWith('## ')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(
                bottom: 8, top: 14),
            child: pw.Container(
              decoration: const pw.BoxDecoration(
                border: pw.Border(
                  bottom: pw.BorderSide(
                    color: PdfColor.fromInt(
                        0xFFD81B60),
                    width: 1,
                  ),
                ),
              ),
              padding: const pw.EdgeInsets.only(
                  bottom: 4),
              child: pw.Text(
                line.substring(3),
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromInt(
                      0xFFD81B60),
                ),
              ),
            ),
          ),
        );
      }

      // H3 heading
      else if (line.startsWith('### ')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(
                bottom: 6, top: 10),
            child: pw.Text(
              line.substring(4),
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
                color:
                PdfColor.fromInt(0xFF333333),
              ),
            ),
          ),
        );
      }

      // Bullet point
      else if (line.startsWith('- ')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(
                bottom: 5, left: 12),
            child: pw.Row(
              crossAxisAlignment:
              pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  '• ',
                  style: pw.TextStyle(
                    fontSize: 13,
                    color: PdfColor.fromInt(
                        0xFFD81B60),
                    fontWeight:
                    pw.FontWeight.bold,
                  ),
                ),
                pw.Expanded(
                  child: pw.Text(
                    line.substring(2),
                    style: const pw.TextStyle(
                      fontSize: 13,
                      color: PdfColors.black,
                      lineSpacing: 3,
                    ),
                  ),
                ),
              ],
            ),
          ),
        );
      }

      // Divider
      else if (line.startsWith('---')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(
                vertical: 10),
            child: pw.Divider(
              color: PdfColors.grey300,
            ),
          ),
        );
      }

      // Emoji lines like 📌 💡 🔑
      else if (line.contains('📌') ||
          line.contains('💡') ||
          line.contains('🔑')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(
                bottom: 8, top: 12),
            child: pw.Text(
              line.replaceAll('##', '').trim(),
              style: pw.TextStyle(
                fontSize: 15,
                fontWeight: pw.FontWeight.bold,
                color: PdfColor.fromInt(
                    0xFFD81B60),
              ),
            ),
          ),
        );
      }

      // Normal text
      else {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(
                bottom: 5),
            child: pw.Text(
              line,
              style: const pw.TextStyle(
                fontSize: 13,
                color: PdfColors.black,
                lineSpacing: 4,
              ),
            ),
          ),
        );
      }
    }

    return widgets;
  }

  // ── Share PDF ─────────────────────────────────────────────
  static Future<void> sharePdf(File pdfFile) async {
    await Share.shareXFiles(
      [XFile(pdfFile.path)],
      subject: 'Notes from NoteMate',
      text: 'Sharing notes generated by NoteMate',
    );
  }

  // ── Preview PDF in viewer ─────────────────────────────────
  static Future<void> previewPdf(
      File pdfFile) async {
    await Printing.layoutPdf(
      onLayout: (_) => pdfFile.readAsBytes(),
    );
  }
}