import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfGeneratorService {
  /// Generates a PDF from note content and saves it
  /// to the app's documents directory.
  /// Returns the saved file path on success.
  static Future<String> generateNotePdf({
    required String title,
    required String content,
    required List<String> tags,
    String teacherName = '',
    String noteType = 'note',
  }) async {
    try {
      final pdf = pw.Document();

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(40),
          build: (pw.Context context) {
            return [
              // ── Header ──────────────────────────────
              pw.Container(
                padding: const pw.EdgeInsets.all(16),
                decoration: pw.BoxDecoration(
                  color: const PdfColor.fromInt(0xFFD81B60),
                  borderRadius:
                  const pw.BorderRadius.all(
                      pw.Radius.circular(8)),
                ),
                child: pw.Column(
                  crossAxisAlignment:
                  pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      title,
                      style: pw.TextStyle(
                        fontSize: 22,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.white,
                      ),
                    ),
                    if (teacherName.isNotEmpty) ...[
                      pw.SizedBox(height: 6),
                      pw.Text(
                        'Teacher: $teacherName',
                        style: const pw.TextStyle(
                          fontSize: 13,
                          color: PdfColors.white,
                        ),
                      ),
                    ],
                    pw.SizedBox(height: 6),
                    pw.Text(
                      'Type: ${noteType[0].toUpperCase()}${noteType.substring(1)} • ${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}',
                      style: const pw.TextStyle(
                        fontSize: 11,
                        color: PdfColors.white,
                      ),
                    ),
                  ],
                ),
              ),

              pw.SizedBox(height: 16),

              // ── Tags ─────────────────────────────────
              if (tags.isNotEmpty) ...[
                pw.Wrap(
                  spacing: 6,
                  runSpacing: 4,
                  children: tags.map((tag) {
                    return pw.Container(
                      padding:
                      const pw.EdgeInsets.symmetric(
                          horizontal: 10,
                          vertical: 4),
                      decoration: pw.BoxDecoration(
                        color: const PdfColor.fromInt(
                            0xFFE5D1E8),
                        borderRadius:
                        const pw.BorderRadius.all(
                            pw.Radius.circular(20)),
                      ),
                      child: pw.Text(
                        '# $tag',
                        style: pw.TextStyle(
                          fontSize: 11,
                          color: const PdfColor.fromInt(
                              0xFFD81B60),
                          fontWeight:
                          pw.FontWeight.bold,
                        ),
                      ),
                    );
                  }).toList(),
                ),
                pw.SizedBox(height: 16),
              ],

              // ── Divider ───────────────────────────────
              pw.Divider(
                  color: const PdfColor.fromInt(
                      0xFFE5D1E8)),
              pw.SizedBox(height: 12),

              // ── Content ───────────────────────────────
              // Parse markdown-like content into PDF
              ..._parseContent(content),

              pw.SizedBox(height: 20),

              // ── Footer ────────────────────────────────
              pw.Divider(
                  color: const PdfColor.fromInt(
                      0xFFE5D1E8)),
              pw.SizedBox(height: 8),
              pw.Text(
                'Generated by NoteMate',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey,
                ),
                textAlign: pw.TextAlign.center,
              ),
            ];
          },
        ),
      );

      // Save to app documents directory
      final dir = await getApplicationDocumentsDirectory();
      final pdfDir =
      Directory('${dir.path}/NoteMate_PDFs');
      if (!await pdfDir.exists()) {
        await pdfDir.create(recursive: true);
      }

      // Clean filename
      final safeName = title
          .replaceAll(RegExp(r'[^\w\s-]'), '')
          .replaceAll(' ', '_')
          .toLowerCase();
      final timestamp =
          DateTime.now().millisecondsSinceEpoch;
      final filePath =
          '${pdfDir.path}/${safeName}_$timestamp.pdf';

      final file = File(filePath);
      await file.writeAsBytes(await pdf.save());

      debugPrint('PDF saved: $filePath');
      return filePath;
    } catch (e) {
      debugPrint('PDF generation error: $e');
      return '';
    }
  }

  // ── Parse simple markdown into PDF widgets ────────
  static List<pw.Widget> _parseContent(
      String content) {
    final List<pw.Widget> widgets = [];
    final lines = content.split('\n');

    for (final line in lines) {
      if (line.startsWith('# ')) {
        widgets.add(pw.Text(
          line.substring(2),
          style: pw.TextStyle(
            fontSize: 18,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.black,
          ),
        ));
        widgets.add(pw.SizedBox(height: 8));
      } else if (line.startsWith('## ')) {
        widgets.add(pw.Text(
          line.substring(3),
          style: pw.TextStyle(
            fontSize: 15,
            fontWeight: pw.FontWeight.bold,
            color: const PdfColor.fromInt(0xFFD81B60),
          ),
        ));
        widgets.add(pw.SizedBox(height: 6));
      } else if (line.startsWith('### ')) {
        widgets.add(pw.Text(
          line.substring(4),
          style: pw.TextStyle(
            fontSize: 13,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.black,
          ),
        ));
        widgets.add(pw.SizedBox(height: 4));
      } else if (line.startsWith('- ') ||
          line.startsWith('* ')) {
        widgets.add(pw.Row(
          crossAxisAlignment:
          pw.CrossAxisAlignment.start,
          children: [
            pw.Text('• ',
                style: const pw.TextStyle(
                    fontSize: 13,
                    color: PdfColors.black)),
            pw.Expanded(
              child: pw.Text(
                line.substring(2),
                style: const pw.TextStyle(
                    fontSize: 13,
                    color: PdfColors.black),
              ),
            ),
          ],
        ));
        widgets.add(pw.SizedBox(height: 3));
      } else if (line.trim().isEmpty) {
        widgets.add(pw.SizedBox(height: 8));
      } else {
        // Strip ** bold markers for PDF
        final cleaned =
        line.replaceAll(RegExp(r'\*\*(.+?)\*\*'),
            r'$1');
        widgets.add(pw.Text(
          cleaned,
          style: const pw.TextStyle(
            fontSize: 13,
            color: PdfColors.black,
            lineSpacing: 1.5,
          ),
        ));
        widgets.add(pw.SizedBox(height: 4));
      }
    }

    return widgets;
  }
}